
source 'https://github.com/CocoaPods/Specs.git'

target 'CoreSDKDemo' do

pod 'LJLogView', '~> 1.0.0'

pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git"
pod 'DroiCoreSDK', '~> 0.5.1991'
 post_install do |installer|
require './Pods/DroiCoreSDK/scripts/postInstall.rb'
DroiCoreParser.installParser()
#end
end
